name: Sync

on:
  push:

  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
            
      - name: Sync upstream changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # API_DATA=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY})
          API_DATA=$(gh api repos/${GITHUB_REPOSITORY})
          UPSTREAM_REPO=$(jq -r '.parent.full_name' <<< ${API_DATA})
          # git config user.name "${GITHUB_ACTOR}"
          # git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com";
          git config --local user.name  "GitHub Actions";
          git remote add upstream https://github.com/${UPSTREAM_REPO}.git
          git fetch upstream --prune --prune-tags
          git merge upstream/$(git branch --show-current) --allow-unrelated-histories
          git push -f
          git push --tag -f

      # - uses: imba-tjd/rebase-upstream-action@master
      #   with:
      #     branch: $(git branch --show-current)

      # - name: set env
      #   run: |
      #     export branch="$(git branch --show-current)"

      # - name: Sync upstream changes
      #   id: sync
      #   uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      #   with:
      #     target_sync_branch: ${{ env.branch }}
      #     # REQUIRED 'target_repo_token' exactly like this!
      #     target_repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     upstream_sync_branch: main
      #     upstream_sync_repo: touhoured/sandbox
